import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "./components/Header";
import Footer from "./components/Footer";

const no_name_reg = localFont({
  src: "../public/fonts/no_name_37_Regular.otf",
  variable: "--font-no-name-regular",
})

const open_sans_semibold = localFont({
  src: "../public/fonts/OpenSans-Semibold.ttf",
  variable: "--font-open-sans-semibold",
})

const open_sans_regular = localFont({
  src: "../public/fonts/OpenSans-Regular.ttf",
  variable: "--font-open-sans-regular",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${no_name_reg.variable} ${open_sans_semibold.variable} ${open_sans_regular.variable} antialiased`}
      >
        <div className="h-screen flex flex-col">
        <Header></Header>
        <main className="flex-1 overflow-auto bg-[#85A425] flex flex-col">
          {children}  
          <Footer/>
        </main>
      </div>
      </body>
    </html>
  );
}
